services:
  # Development database only
  db:
    image: postgres:16-alpine
    container_name: monman-db-dev
    environment:
      POSTGRES_USER: monman_user
      POSTGRES_PASSWORD: monman_pass
      POSTGRES_DB: monman_db
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U monman_user -d monman_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data_dev:
    driver: local
